spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=sanjay
spring.datasource.password=1234
server.port=8087
spring.jpa.hibernate.ddl-auto=update
ranking.default-weight=1.5
ranking.max-score=100