spring.application.name=Product-Ranking-System
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=sanjay
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
server.port=8082
# Disable the Open-In-View warning (Best practice for APIs)
spring.jpa.open-in-view=false

# Make your SQL logs look pretty and readable (Optional, but great for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true